package com.dmdelivery.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * 
 * This is the DMdelivery SOAP webservice.
 * 
 * In order to be able to use this webservice, you need to have a login for
 * DMdelivery. A login consists of a username and a password. Each SOAP call in
 * the webservice needs this username and password for access! Please inquire
 * with the DMdelivery administrator for a login.
 * 
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DMdeliverySoapAPI service = new DMdeliverySoapAPI();
 * DMdeliverySoapAPIPort portType = service.getDMdeliverySoapAPIPort();
 * portType.checkHealth(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DMdeliverySoapAPI", targetNamespace = "http://dmdelivery.com/webservice/", wsdlLocation = "https://fields.dmdelivery.com/x/soap-v4.1/wsdl.php")
public class DMdeliverySoapAPI extends Service {

	private final static URL DMDELIVERYSOAPAPI_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.dmdelivery.webservice.DMdeliverySoapAPI.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.dmdelivery.webservice.DMdeliverySoapAPI.class
					.getResource(".");
			url = new URL(baseUrl,
					"https://fields.dmdelivery.com/x/soap-v4.1/wsdl.php");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'https://fields.dmdelivery.com/x/soap-v4.1/wsdl.php', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DMDELIVERYSOAPAPI_WSDL_LOCATION = url;
	}

	public DMdeliverySoapAPI(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DMdeliverySoapAPI() {
		super(DMDELIVERYSOAPAPI_WSDL_LOCATION, new QName(
				"http://dmdelivery.com/webservice/", "DMdeliverySoapAPI"));
	}

	/**
	 * 
	 * @return returns DMdeliverySoapAPIPort
	 */
	@WebEndpoint(name = "DMdeliverySoapAPIPort")
	public DMdeliverySoapAPIPort getDMdeliverySoapAPIPort() {
		return super.getPort(new QName("http://dmdelivery.com/webservice/",
				"DMdeliverySoapAPIPort"), DMdeliverySoapAPIPort.class);
	}

}
